fix+refactor: added menu, fixed coords, general improvements
Qbox-project/qbx_vineyard pull request #16
Opened 2023-12-13 15:19 UTC by dusan01

## Description

1. Moved processing to a single place
2. Used ox_lib context menu for processing
3. Changed item adding and checking to use ox_inventory exports
4. Added blips
5. Removed useless threads
6. Renamed functions

## Checklist

- [x] I have personally loaded this code into an updated Qbox project and checked all of its functionality.
- [x] My pull request fits the contribution guidelines & code conventions.

2023-12-14 00:08 UTC, D4isDAVID requested changes

2023-12-14 00:08 UTC, D4isDAVID commented on client/main.lua
> +end)
```suggestion
if isLoggedIn then init() end
```
Can be simplified since this code runs when the resource starts anyway.

2023-12-14 00:08 UTC, D4isDAVID commented on client/main.lua
> +    if config.useBlips then setLocationsBlip() end
Maybe move this check to `setLocationsBlip` directly instead of creating a wrapper for it? It would make sense since the function that creates blips shouldn't do anything if they're disabled.

2023-12-14 00:08 UTC, D4isDAVID commented on client/main.lua
> +        }) then
Not sure about this spacing...

2023-12-14 01:24 UTC, D4isDAVID approved these changes

2023-12-15 02:13 UTC, MafewTM approved these changes

2023-12-15 02:15 UTC, merged